### ISSUE TITLE
row 27116 in atp_players.csv

### ISSUE THREAD

**Issue by GoldenSlam** [JeffSackmann/tennis_atp#1]
The player name seems to have got some HTML doctype text in it somehow. Rows 36445, 36448 and 38829 also have the same HTML data.

**Comment by GoldenSlam** [comment]
row 23426 also has some weird data that looks like perhaps a tournament name or something.

**Comment by JeffSackmann** [comment]
Thanks. I'll fix these for a planned update in the next few days.
