### ISSUE TITLE
2002 wrexham ch

### ISSUE THREAD

**Issue by JeffSackmann** [JeffSackmann/tennis_atp#10]
[per email from e.j., which included corrected data for this event]

I ran into a bit of a snag in the 2002 data. The Wrexham Challenger event that was played that year only has 29 of the 31 matches included, and they're not in a conventional order in the file. Those 29 matches also show up twice in the Challenger file, and one more time in the ATP file.

**Comment by bazzaar** [comment]
Hi,

(I was just about to post this as a new issue, then saw this was still an open issue.)

I can confirm that the match data (29 matches total, unconventional ordering) for this tournament, occurs 3 times in the repo (twice in the Challenger, once in the ATP) at the time of writing this comment (02-Dec-2018).

This probably doesn't help much :-)   
bazzaar

**Comment by JeffSackmann** [comment]
filled in the missing matches, and I believe it's only included once. i'm not concerned about the unconventional match order.
