### ISSUE TITLE
Recent data - any news about when the latest tournaments are planned to be added?

### ISSUE THREAD

**Issue by AndreiArba** [JeffSackmann/tennis_atp#104]
Hello, 

Could you give me any info about when the most recent tournaments are planned to be added?
Or that won't happen in the near future?

Thank you and sorry if this should not be added as "issue".

**Comment by bazzaar** [comment]
I have no more knowledge on this aspect than you, other than to point you towards the following web page : `http://www.tennisabstract.com/blog/tennis-abstract-contact/` where, in the page text, the author specifically asks folk to kindly not request updates to these public repo's.

So I would suggest that you might want to close this issue?

hope this helps,
bazzaar

**Comment by AndreiArba** [comment]
ok, thank you

**Comment by mcekovic** [comment]
Hello, anyone interested in creating a new free Tennis Raw Data repository that will:
- Use structured format (XML, JSON or YAML) for players, rankings and most importantly matches data
- And thus be more human readable and easier human editable (to spot and correct mistakes)
- Using normalized data model for matches, avoiding data repetition (like tournament name, level, surface... extracted in the dedicated entity, i.e. tournament event)
- Will be automatically updated every Monday (i.e. creating scripts that would run every Monday to update the repo)
- Will have documented and established procedure for merging pull requests with data corrections and additions of missing data.

**Comment by onouris41** [comment]
> 
> 
> Hello, anyone interested in creating a new free Tennis Raw Data repository that will:
> 
>     * Use structured format (XML, JSON or YAML) for players, rankings and most importantly matches data
> 
>     * And thus be more human readable and easier human editable (to spot and correct mistakes)
> 
Hello @mcekovic!
i'm interested in creating and supporting your idea. I've been thinking about it for a few weeks/months and I can present this.


>     * Using normalized data model for matches, avoiding data repetition (like tournament name, level, surface... extracted in the dedicated entity, i.e. tournament event)
> 
>     * Will be automatically updated every Monday (i.e. creating scripts that would run every Monday to update the repo)
> 
>     * Will have documented and established procedure for merging pull requests with data corrections and additions of missing data.

**Comment by wazo11** [comment]
@onouris41 @mcekovic 
I'm also interested in joining in on this, pm me if you need an extra hand
