### ISSUE TITLE
Need 2019 data

### ISSUE THREAD

**Issue by albertomota-codes** [JeffSackmann/tennis_atp#106]
how can i help, or where can i get more updated data?
Your data is amazing.

**Comment by BigTimeStats** [comment]
Hey @albertomota-codes 

I'm testing publishing this data myself. Take a look: https://github.com/BigTimeStats/atp-tennis

I updated the same/similar data from 9-17-2018 until 3-20-2019, overlapping on Jeff Sackmann's St. Petersburg tourney for you to do any data validation checks.

If the data is useful for you, please consider giving attribution to motivate me to publish more. Enjoy!

-Adam

**Comment by albertomota-codes** [comment]
I am not really sure what do you mean by "attribution". But i am planning in try some ML with your data, for sure i will give attribution in that repo. The ML i am planning is only for academic purposes.

**Comment by BigTimeStats** [comment]
Awesome, good luck on the project. Just meant a link back or some credit for providing the data :)
