### ISSUE TITLE
ATP Rankings : discrepancies in the rankings files pre- and post- fe99318 commit.

### ISSUE THREAD

**Issue by bazzaar** [JeffSackmann/tennis_atp#108]
Hi,

I'm comparing the ATP rankings data pre- and post- fe99318 commit (early May 2019) to get an idea exactly what's changed, and I've noticed there's a few discrepancies that might not have been intended as part of the commit work :

Some of the post-fe99318 rankings files have null value in the 4th column ('points'), instead of zero. While this might be a more accurate picture, it isn't consistent with what has gone before.

|     rankings file      |null count|
|------------------------|----------|
|atp_rankings_70s.csv    |  11003   |
|atp_rankings_80s.csv    |  265733  |
|atp_rankings_90s.csv    |  54596   |
|atp_rankings_00s.csv    |  8       |
|atp_rankings_10s.csv    |  2       |
|atp_rankings_current.csv|  0       |

This is a fairly simple problem to deal with though, I just used `sed 's/,$/,0/' filename` to convert the new files.

A perhaps more significant discrepancy occurs in the atp_rankings_70s.csv file where it seems that many of the ranking list dates have changed compared with the data in place prior to the commit : 

| before | after  | delta |
|--------|--------|-------|
|19730823|19730827|+4 days|
|19730913|19730917|+4 days|
|19730926|19731001|+5 days|
|19731015|19731015|+0 days|
|19731031|19731105|+5 days|
|19731126|19731126|+0 days|
|19731214|19731217|+3 days|
|19740302|19740304|+2 days|
|19740419|19740422|+3 days|
|19740501|19740506|+5 days|
|19740603|19740603|+0 days|
|19740729|19740729|+0 days|
|19740809|19740812|+3 days|
|19740904|19740909|+5 days|
|19740927|19740930|+3 days|
|19741106|19741111|+5 days|
|19741220|19741223|+3 days|
|19750117|19750120|+3 days|
|19750305|19750310|+5 days|
|19750408|19750414|+6 days|
|19750430|19750505|+5 days|
|19750602|19750602|+0 days|
|19750626|19750630|+4 days|
|19751215|19751215|+0 days|
|19760614|19760614|+0 days|
|19761212|19761213|+1 days|
|19770702|19770704|+2 days|
|19771231|19780102|+2 days|
|19780116|19780116|+0 days|
|19780712|19780717|+5 days|
|19781231|19790101|+1 days|
|19791226|19791231|+5 days|

I checked the 'official' dates on the ATP site, and it's the data from before the fe99318 commit that matches, not the new changed dates. 

I'm considering staying with the pre- fe99318 commit ranking list dates for this datafile?

#### An additional note just to say that issue #82 ('Zverev Sr') still needs addressing, in fact the post-fe99813 `atp_rankings_80s.csv` file seems to have reverted the partly erroneous 8c2645f commit (which substituted id#200603, instead of the intended id#200630, for the incorrect id#100644 [though just for the rankings part of the work]).

`egrep '100644|200630|200603' atp_players.csv
100644,Alexander,Zverev,R,19970420,GER
200603,Simon,Yastremskiy,R,19980105,UKR
200630,Alexander,Zverev Sr,R,19600122,RUS`

`~/temp> ls *.csv
atp_rankings_80s.csv
~/temp> egrep -c '100644' atp_rankings_80s.csv
219     <<<< these should all belong to Zverev Sr id#200630
~/temp> egrep -c '200630' atp_rankings_80s.csv
0
~/temp> egrep -c '200603' atp_rankings_80s.csv
0`
  
Hope this helps,
bazzaar

**Comment by JeffSackmann** [comment]
I changed the ranking dates so that all are mondays, in line with tournament start dates and later years when all ranking dates were mondays.. i'm not concerned about the nulls.
