### ISSUE TITLE
Underlying time zone

### ISSUE THREAD

**Issue by lksfsh** [JeffSackmann/tennis_atp#115]
What is the underlying time zone of the data? Is the time zone consistent for the whole dataset? Are daylight savings time changes considered or not?

**Comment by JeffSackmann** [comment]
there are no times in the data.

**Comment by lksfsh** [comment]
Actually, there is. The data contains tourney_date. Every date has an underlying time stamp, which has an underlying time zone. This time zone and the existence of dst changes is what the question is about.
