### ISSUE TITLE
Meaning of DEF and W/O in the column score

### ISSUE THREAD

**Issue by CesarRoaldes** [JeffSackmann/tennis_atp#120]
Hi,
I'm currently trying to predict match time using this rich dataset (thank you for this work by the way), but i'm wonderning what is the meaning DEF and W/O in the column score?
We also found some RET which we assumed means retirement and some dates instead of the score.

Thanks in advance!

**Comment by JeffSackmann** [comment]
w/o = walkover
def = default

**Comment by CesarRoaldes** [comment]
Thank you!
