### ISSUE TITLE
the percents are too big 

### ISSUE THREAD

**Issue by RollandWeiss** [JeffSackmann/tennis_atp#122]
http://www.tennisabstract.com/cgi-bin/wplayer-classic.cgi?p=NataliaOrlova&f=ACareerqqB0

Time Span: Career; Sur... | 114-117 (49%) | 15-21 (42%) | 0.4% | 28349.8% | 0.3% | 0.0% | 68.5% | -61.83

**Comment by JeffSackmann** [comment]
this is not a bug tracker for the tennis abstract website. you are referring to data that is not in this repo.

**Comment by RollandWeiss** [comment]
Okay, but there is a place where the bugs can be placed? Or the site was left
