### ISSUE TITLE
double results

### ISSUE THREAD

**Issue by RicardoPotters** [JeffSackmann/tennis_atp#123]
I noticed that some tournements are double in the data (atp_matches):

tourney_date | winner_id | winner_name | Aantal   van match_num
-- | -- | -- | --
30-12-1968 | 100030 | Fred Stolle | 2
13-1-1969 | 100100 | Tony Roche | 2
29-1-1969 | 100100 | Tony Roche | 2
9-11-1970 | 100074 | Arthur Ashe | 2
29-10-1973 | 100119 | Ilie Nastase | 2
28-10-1974 | 100261 | Brian Gottfried | 2
14-4-1975 | 100144 | Robert Lutz | 2
27-10-1975 | 100084 | Tom Okker | 2
25-10-1976 | 100232 | Eddie Dibbs | 2
7-2-1977 | 100119 | Ilie Nastase | 2
31-10-1977 | 100297 | Corrado Barazzutti | 2
30-1-1978 | 100309 | Raul Ramirez | 2
29-10-1979 | 100286 | Harold Solomon | 2
22-11-1982 | 100115 | Jaime Fillol | 2

thanks for the great work!

**Comment by JeffSackmann** [comment]
thanks for letting me know, now fixed
