### ISSUE TITLE
ATP Matches Abbreviations

### ISSUE THREAD

**Issue by DMB2L** [JeffSackmann/tennis_atp#124]
Dear Jeff,

We are attempting to use your database (ATP 2019 Matches) to determine the most important variables for predicting the outcome of a Tennis Match as part of our University's sports project. However, we were wondering if you could help us understand some abbreviations. Specifically:

1. w_bpFaced
2. w_bpSaved
3. w_SvGms
4. w_svpt
5. w_df

Thank you for your time,
Kind regards,
Alex

**Comment by JeffSackmann** [comment]
I've added a data dictionary here:
https://github.com/JeffSackmann/tennis_atp/blob/master/matches_data_dictionary.txt
