### ISSUE TITLE
Double data

### ISSUE THREAD

**Issue by lebelge5** [JeffSackmann/tennis_atp#127]
Hi,

1- In your file atp_rankings_10s, the data for 20181231 are all duplicated.
 2- between 20181231 and 20190719, there are only around 670 players ranked, versus around 1800 before and after. Is there a reason for that? 

Thank you

**Comment by JeffSackmann** [comment]
sorry for the late response. looks like I fixed the duplicated 2018/12/31 rankings at some point in the past.

At the beginning of 2019, the ATP changed how the rankings treated low-level events, with the goal of having fewer pro players. The ITF developed its own separate ranking system, which included everyone who played ITFs and ITF qualifiers, and included thousands of players. In general, the players didn't like it, and the ATP went back to the old way midway through 2019.
more here: https://lastwordonsports.com/tennis/2019/08/06/atp-itf-ranking-system/
