### ISSUE TITLE
information about the hand and wikipedia pages

### ISSUE THREAD

**Issue by paulasaavedra** [JeffSackmann/tennis_atp#139]
Hi Jeff. It is always good to collaborate with your work. I leave you information about the hand of some players and the wikipedia page, if they have it. The format is: (separated only by one space)
hand /player id /player name /wikipedia page

In a few days I will complete more data, which I have not finished yet.

L 126609 Patrik Niklas Salminen https://en.wikipedia.org/wiki/Patrik_Niklas-Salminen
R 200045 Anthony Susanto
R 126526 Soren Hess Olesen https://en.wikipedia.org/wiki/S%C3%B8ren_Hess-Olesen
R 105798 Tilen Zitnik https://en.wikipedia.org/wiki/Tilen_%C5%BDitnik
L 144826 Aziz Dougaz https://en.wikipedia.org/wiki/Aziz_Dougaz
R 144949 Menelaos Efstathiou https://en.wikipedia.org/wiki/Menelaos_Efstathiou
R 123315 Nicholas Campbell
R 138846 Hong Kit Jack Wong https://en.wikipedia.org/wiki/Wong_Hong-kit
R 134120 Kuan Yi Lee https://en.wikipedia.org/wiki/Lee_Kuan-yi
R 200125 Mykyta Mashtakov
R 105870 Yannick Hanfmann https://en.wikipedia.org/wiki/Yannick_Hanfmann
R 127157 Daniel Altmaier https://en.wikipedia.org/wiki/Daniel_Altmaier
R 124186 Alexandre Muller https://en.wikipedia.org/wiki/Alexandre_M%C3%BCller
R 126127 Benjamin Bonzi https://en.wikipedia.org/wiki/Benjamin_Bonzi
R 111515 Thai Son Kwiatkowski https://en.wikipedia.org/wiki/Thai-Son_Kwiatkowski
R 117360 Marc Polmans https://en.wikipedia.org/wiki/Marc_Polmans
R 105181 Miljan Zekic https://en.wikipedia.org/wiki/Miljan_Zeki%C4%87
R 200516 Patrick Kypson https://en.wikipedia.org/wiki/Patrick_Kypson
R 126185 Evgenii Tiurnev https://en.wikipedia.org/wiki/Evgenii_Tiurnev
R 126208 Yusuke Takahashi https://en.wikipedia.org/wiki/Yusuke_Takahashi
R 126128 Roman Safiullin https://en.wikipedia.org/wiki/Roman_Safiullin
R 106120 Ricardo Ojeda Lara https://en.wikipedia.org/wiki/Ricardo_Ojeda_Lara
R 132482 Liam Caruana https://en.wikipedia.org/wiki/Liam_Caruana
R 106391 Adrian Bodmer https://en.wikipedia.org/wiki/Adrian_Bodmer
R 200483 Peter August Anker
R 200401 Amir Hossein Badi
R 106396 Cheng Yu Yu
R 207421 Alex Fairbanks
R 202090 Adrian Andreev https://en.wikipedia.org/wiki/Adrian_Andreev
R 200574 Alexander Donski https://en.wikipedia.org/wiki/Alexander_Donski
R 200624 Sebastian Korda https://en.wikipedia.org/wiki/Sebastian_Korda
L 200384 Hugo Gaston https://en.wikipedia.org/wiki/Hugo_Gaston
R 126174 Youssef Hossam https://en.wikipedia.org/wiki/Youssef_Hossam
R 200460 John Bryan Decasa Otico
L 207738 Brandon Perez
R 106072 Alexey Vatutin https://en.wikipedia.org/wiki/Alexey_Vatutin
R 200436 Zsombor Piros https://en.wikipedia.org/wiki/Zsombor_Piros
R 200611 Elliot Benchetrit https://en.wikipedia.org/wiki/Elliot_Benchetrit
R 126125 Maxime Janvier https://en.wikipedia.org/wiki/Maxime_Janvier
R 126845 Max Purcell https://en.wikipedia.org/wiki/Max_Purcell
R 144645 Zdenek Kolar https://en.wikipedia.org/wiki/Zden%C4%9Bk_Kol%C3%A1%C5%99
L 144817 Marc Andrea Huesler https://en.wikipedia.org/wiki/Marc-Andrea_Huesler
R 133297 Yosuke Watanuki https://en.wikipedia.org/wiki/Yosuke_Watanuki
R 127339 Borna Gojo https://en.wikipedia.org/wiki/Borna_Gojo
R 202385 Jenson Brooksby https://en.wikipedia.org/wiki/Jenson_Brooksby
R 138431 Darko Bojanovic https://en.wikipedia.org/wiki/Darko_Bojanovi%C4%87
R 207139 Palaphoom Kovapitukted https://en.wikipedia.org/wiki/Palaphoom_Kovapitukted
R 133975 Benjamin Hassan
R 202103 Francisco Cerundolo https://es.wikipedia.org/wiki/Francisco_Cer%C3%BAndolo
R 200368 Jack Mingjie Lin https://en.wikipedia.org/wiki/Jack_Mingjie_Lin
R 207182 Emilio Nava
R 106203 Pedro Sakamoto
R 206173 Jannik Sinner https://es.wikipedia.org/wiki/Jannik_Sinner
R 126237 Gian Marco Moroni
R 208260 Zachary Svajda https://en.wikipedia.org/wiki/Zachary_Svajda
R 144946 Rayane Roumane https://en.wikipedia.org/wiki/Rayane_Roumane
R 208230 Alibek Kachmazov https://en.wikipedia.org/wiki/Alibek_Kachmazov
R 144984 Artem Dubrivnyy https://en.wikipedia.org/wiki/Artem_Dubrivnyy
R 122298 Botic van de Zandschulp https://en.wikipedia.org/wiki/Botic_van_de_Zandschulp
R 200526 Juan Lugo
R 209226 Adolfo Daniel Vallejo
R 208476 Kyle Johnson https://en.wikipedia.org/wiki/Kyle_Johnson_(tennis)
R 207134 Fitriadi M Rifqi
R 208937 Kasidit Samrej https://en.wikipedia.org/wiki/Kasidit_Samrej
R 208597 Chak Lam Coleman Wong
R 106388 Pak Long Yeung https://en.wikipedia.org/wiki/Yeung_Pak-long
R 207852 Wai Yu Kai
R 144841 Christian Sigsgaard https://en.wikipedia.org/wiki/Christian_Sigsgaard
R 208029 Holger Rune https://es.wikipedia.org/wiki/Holger_Vitus_N%C3%B8dskov_Rune
R 125842 Adam Moundir https://en.wikipedia.org/wiki/Adam_Moundir
R 126328 Gabriel Donev https://en.wikipedia.org/wiki/Gabriel_Donev
R 200343 David Szintai https://en.wikipedia.org/wiki/D%C3%A1vid_Szintai
L 208364 Franco Roncadelli
R 106408 Mario Vilella Martinez  https://es.wikipedia.org/wiki/Mario_Vilella_Mart%C3%ADnez
L 207680 Facundo Diaz Acosta https://es.wikipedia.org/wiki/Facundo_D%C3%ADaz_Acosta
R 208108 Brian Shi
R 206909 Brandon Nakashima https://es.wikipedia.org/wiki/Brandon_Nakashima
R 208004 Harold Mayot https://en.wikipedia.org/wiki/Harold_Mayot
R 207989 Carlos Alcaraz Garfia https://en.wikipedia.org/wiki/Carlos_Alcaraz
R 144642 Marcelo Tomas Barrios Vera https://en.wikipedia.org/wiki/Marcelo_Tom%C3%A1s_Barrios_Vera
R 200670 J.J. Wolf https://en.wikipedia.org/wiki/Jeffrey_John_Wolf
R 202195 Maxime Cressy https://en.wikipedia.org/wiki/Maxime_Cressy
R 126239 Arthur Rinderknech https://en.wikipedia.org/wiki/Arthur_Rinderknech
R 200303 Pavel Kotov https://en.wikipedia.org/wiki/Pavel_Kotov_(tennis)
R 126964 Vitaliy Sachko https://en.wikipedia.org/wiki/Vitaliy_Sachko
R 209867 Daniil Ostapenkov
R 133979 Hasan Ibrahim
R 202261 Otto Virtanen https://en.wikipedia.org/wiki/Otto_Virtanen
R 209868 Kaipo Marshall
R 132374 Jesse Flores https://en.wikipedia.org/wiki/Jesse_Flores_(tennis)
R 209869 Rodrigo Crespo Piedra
R 202120 Rowland Phillips https://en.wikipedia.org/wiki/Rowland_Phillips_(tennis)
R 209080 Blaise Bicknell
R 206600 Zura Tkemaladze
R 202246 Nikoloz Davlianidze
R 209866 Karlis Ozolins https://en.wikipedia.org/wiki/K%C4%81rlis_Ozoli%C5%86%C5%A1
R 202300 Phuong Van Nguyen
L 209872 Thehan Sanjaya Wijemanne
R 209873 Eric Jr. Olivarez 
R 144869 Tomas Martin Etcheverry https://en.wikipedia.org/wiki/Tom%C3%A1s_Etcheverry
R 126409 Hugo Grenier https://en.wikipedia.org/wiki/Hugo_Grenier
R 202398 Michael Vrbensky https://en.wikipedia.org/wiki/Michael_Vrbensk%C3%BD
R 111454 Li Tu https://en.wikipedia.org/wiki/Li_Tu
R 208278 Shintaro Mochizuki https://en.wikipedia.org/wiki/Shintaro_Mochizuki
R 127760 Lukas Klein https://en.wikipedia.org/wiki/Luk%C3%A1%C5%A1_Klein
L 207678 Juan Manuel Cerundolo https://en.wikipedia.org/wiki/Juan_Manuel_Cer%C3%BAndolo

In this case the player's name is wrong by one letter:

Incorrect:
R 126939 Khumoun Sultanov https://en.wikipedia.org/wiki/Khumoyun_Sultanov
Correct:
R 126939 Khumoyun Sultanov https://en.wikipedia.org/wiki/Khumoyun_Sultanov

Thank you Jeff!

**Comment by JeffSackmann** [comment]
thanks Paula!
