### ISSUE TITLE
Some errors in scores

### ISSUE THREAD

**Issue by rinthel** [JeffSackmann/tennis_atp#141]
Hello, first I would like to appreciate you for this great work.

I was writing tennis statistics calculator just for fun, and found some errors in the scores as below:
  - Feb
  - Jun
  - Apr

You can find those using a text editor easily,
and I can also send a PR if you want.

Many thanks!

**Comment by JeffSackmann** [comment]
I forgot to tag this issue, but tour and challenger-level matches have been fixed
https://github.com/JeffSackmann/tennis_atp/commit/c0d1b46e6ca0f12d1f3a3afae82c8cf264de7877

will close the issue when futures have been fixed as well.
