### ISSUE TITLE
Some wrong data - US Open 2020

### ISSUE THREAD

**Issue by Kaurna17** [JeffSackmann/tennis_atp#142]
Hi,

Thanks for this incredible set of data !

For US Open 2020 (tourney_id = 2020-560), the following matches (match_num) have no "SvGms" data (0 game played for both winner and loser) : 149, 173 & 177
The right data is, for winner and loser respectively (winner -- loser) :
149: 24 -- 25
173: 26 -- 25
177: 16--17

Hope it helps,
Thank you

**Comment by JeffSackmann** [comment]
fixed, thanks!
