### ISSUE TITLE
atp_rankings_current.csv missing header row

### ISSUE THREAD

**Issue by RLesser** [JeffSackmann/tennis_atp#149]
Hi,

First off, thank you for creating and maintaining this dataset. It's truly a gift.

I've noticed one consistency issue with the rankings files. The past decade files all have a header row consisting of `ranking_date,rank,player,points`, but the current file seems to be missing the header row.

Please let me know if I have missed something, but if not I'd be happy to put up a pull req to fix (although if the files are auto-generated then it might need to be changed in a script somewhere).

Thanks again!

**Comment by JeffSackmann** [comment]
fixed, thanks. this one is regenerated every week, but it should be fixed going forward as well.
