### ISSUE TITLE
List of all players 

### ISSUE THREAD

**Issue by AdityaMittal11** [JeffSackmann/tennis_atp#161]
Is there a way for me to get a list of all the players in the open era with the year in which they turned pro, the year they retired, their best ranking and if possible their number of grand slams championship wins if any.

**Comment by JeffSackmann** [comment]
the raw data necessary to generate such a list is all here. if you learn the basics of a scripting language such as python, you can extract the list you'd like. not sure if anyone here has the time and inclination to help with requests like these, though.
