### ISSUE TITLE
Is it possible to sort matches by date ?

### ISSUE THREAD

**Issue by CamilleTamoumi** [JeffSackmann/tennis_atp#165]
Hello, for my neural network it is verry important to have matches sorted by date; can you do this ? or add a match date like tourney date; thankiou

**Comment by FBruzzesi** [comment]
I think you could order by `round` after converting it to a ordered categorical column (e.g. [`pandas.Categorical`](https://pandas.pydata.org/docs/reference/api/pandas.Categorical.html) allows you to do that), or use `match_num`, which however it's trickier since its value is:
> a match-specific identifier. Often starting from 1, sometimes counting down from 300, and sometimes arbitrary.

**Comment by JeffSackmann** [comment]
@FBruzzesi is correct. I typically use round. The only time that doesn't work is for round robin matches, and I don't have specific match dates for RR matches.
