### ISSUE TITLE
Possibly a wrong date for Dusseldorf Indoor 1975

### ISSUE THREAD

**Issue by Mick1303** [JeffSackmann/tennis_atp#181]
It might be one of those stupid things when they held the main body of the tournament and the final match months apart. But I can't find any proof of this. Anyway, the Dusseldorf indoor you have dated 1975-05-25, while ATP - 1975-03-10. Tid - 1975-661. Note that other Dusseldorf tournament (Outdoor clay) is dated by 1975-05-26.

**Comment by JeffSackmann** [comment]
i'll assume that 5-25 was an older mistake from the atp, and the new date is correct.
