### ISSUE TITLE
Missing first names, misspellings, miscredited matches

### ISSUE THREAD

**Issue by Mick1303** [JeffSackmann/tennis_atp#185]
Jeff,

I understand that your site is non-commercial and maybe it will be inappropriate on my part… But if you could pay some money for rectifying your data – it would’ve been terrific. Tennis statistics/history always been a hobby for me and I never would’ve dreamed to bring the money, but I’m in a bit of a dire situation. I had to flee my home in Kharkov because of Russian shelling. To my knowledge the building is largely intact, only some windows are shattered. But the shelling escalates and I don’t know whether I will be able to return in a foreseeable future. In a meantime I have to pay for rental apartment in the central Ukraine (town of Mirhorod), where I’m located now. And the prices are rising dramatically…
The company where I work is (or I shall rather  say “was”) also located in the northern part of the city, where the shelling is more intensive, and we had to submit the company building to the military, therefore the projects are largely on halt or terminated altogether. They are able to pay us a portion of the salary still, but it is not enough to keep up with raising prices.
Working with a tennis database kind of distracts me and keeps me sane. I would do it in any case. But if you could help financially – would’ve been good. The amount is what you feel is worth for the findings I provide. My name is Mike (Mykhaylo) Tregubov. 

If you are interested in getting my findings in the form below (for instance), let me know:
T_id,Player,Correct Name,ID,Correct ID,Link
1970-6817,Unknown Rios,Juan Alberto Rios,209599,N/A,https://www.atptour.com/en/scores/archive/san-juan/6817/1970/results
1970-6817,Unknown Orasz,Bobby Odasz,209601,209596,https://www.tennisarchives.com/edition/?v=9751
1968-2029,Unknown Doherty,Gerry Doherty,209527,209670,https://www.tennisarchives.com/edition/?v=3831
1968-2029,Unknown Fitzsimmons,Paul Fitzsimmons,209530,209590,https://www.atptour.com/en/scores/archive/dublin/2029/1968/results
4 tournaments,U McDonald,Allan McDonald,109915,100234,i.e https://www.atptour.com/en/scores/archive/madrid/2026/1973/results
1974-309,Unknown Rodrigues,Patricio Rodriguez Chi,209844,100032,https://www.atptour.com/en/scores/archive/madrid/309/1974/results

**Comment by Mick1303** [comment]
In US Open 1969 draw you have “Luis Garcia” (ID 109928) losing to Laver in R128, following ATP. But they clearly have it wrong, because that Luis Garcia has DOB 1969.01.28. Correct player is Luis Augusto Garcia (ID 110849). See https://en.wikipedia.org/wiki/1969_US_Open_%E2%80%93_Men%27s_singles.

**Comment by JeffSackmann** [comment]
Sorry for the late reply -- I don't check this site every day.

First of all, let me say, I'm very sorry to hear that you're going through all that. I can't imagine what it's like. I'm glad that working with the tennis data helps in some small way.

As you say, it is a non-commercial project--it costs me money to keep the tennisabstract.com site up and running, and I don't make anything from tennis these days. So I don't pay for improvements to the data, much as that is probably a good idea.

That said, I may be able to help you a bit ... can you send me an email, at jeffsackmann@gmail.com ? I'll reply faster, and that way the conversation isn't public.
