### ISSUE TITLE
Johnson vs Johnston

### ISSUE THREAD

**Issue by Mick1303** [JeffSackmann/tennis_atp#187]
There is B. Johnston in the draw of Durban – 1969 (ID 209573) and B. Johnson (ID 209605) in the draw of Durban 1970. Even though this difference in the last name is repeated on both ATP site and in TennisArchives, my feeling that it is the same player. Just what are the probabilities of this being otherwise? ))

**Comment by JeffSackmann** [comment]
moved to the duplicates thread
