### ISSUE TITLE
Davis Cup ties mistitled

### ISSUE THREAD

**Issue by Mick1303** [JeffSackmann/tennis_atp#198]
Here I will post the cases when the tie is described not in correspondence with the draw:

Tourn,t_id,year
Davis Cup WG SF: INA vs PAK,1981-D036,1981
Davis Cup WG SF: THA vs IND,1981-D038,1981
Davis Cup WG SF: THA vs IND,1981-D038,1981
Davis Cup WG QF: PHI vs KOR,1982-D046,1982
Davis Cup WG QF: SRI vs IND,1983-D041,1983
Davis Cup WG SF: IND vs THA,1983-D042,1983
Davis Cup WG QF: KOR vs PHI,1983-D047,1983
Davis Cup WG QF: TPE vs THA,1983-D057,1983
Davis Cup WG QF: PAK vs INA,1984-D042,1984
Davis Cup WG F: NZL vs KOR,1985-D048,1985
Davis Cup WG QF: PAK vs KOR,1985-D049,1985
Davis Cup WG SF: PHI vs KOR,1985-D050,1985
Davis Cup WG R1: INA vs PHI,1986-D041,1986
Davis Cup WG QF: THA vs INA,1986-D042,1986
Davis Cup WG QF: KOR vs PAK,1986-D052,1986

All those are not "World Group" but Asia-Oceania divison.

**Comment by JeffSackmann** [comment]
thanks, now fixed. I'm closing this, but feel free to re-open if you find more.

**Comment by Mick1303** [comment]
2002 Group I tournament names are messed up. If you look at https://www.daviscup.com/en/draws-results/historic-format/group-i/asia-oceania.aspx#/2002
you'll see that there is 1st and 2nd round.
t_id,Tourn,Name
2002-D009,Davis Cup G1 R1: ZIM vs POR,DC-Group I 1st Round
2002-D010,Davis Cup G1 R1: AUT vs ISR,DC-Group I 1st Round
2002-D019,Davis Cup G1 QF: THA vs UZB,DC-Group I 1st Round
2002-D020,Davis Cup G1 QF: KOR vs JPN,DC-Group I 1st Round
2002-D021,Davis Cup G1 QF: NZL vs INA,DC-Group I 1st Round
2002-D022,Davis Cup G1 QF: LIB vs IND,DC-Group I 1st Round
2002-D027,Davis Cup G1 QF: BAH vs VEN,DC-Group I 1st Round
2002-D028,Davis Cup G1 QF: CAN vs MEX,DC-Group I 1st Round
2002-D035,Davis Cup G1 SF: THA vs JPN,DC-Group I 2nd Round
2002-D036,Davis Cup G1 SF: NZL vs IND,DC-Group I 2nd Round
2002-D037,Davis Cup G1 QF: ITA vs FIN,DC-Group I 2nd Round
2002-D038,Davis Cup G1 QF: ZIM vs BLR,DC-Group I 2nd Round
2002-D039,Davis Cup G1 QF: ROU vs AUT,DC-Group I 2nd Round
2002-D040,Davis Cup G1 QF: BEL vs GRE,DC-Group I 2nd Round
2002-D045,Davis Cup G1 SF: VEN vs ECU,DC-Group I 2nd Round
2002-D046,Davis Cup G1 SF: CAN vs CHI,DC-Group I 2nd Round

**Comment by Mick1303** [comment]
Davis Cup EUR QF: HKG vs CHN (tid 1986-D022). Title is incorrect. It shall be "Eastern Eastern Quarterfinal".

**Comment by Mick1303** [comment]
Davis Cup AME SF: JPN vs CHN (tid 1986-D023). Title is incorrect. It shall be "Eastern Semifinal".

**Comment by Mick1303** [comment]
All of  1985-D018, 1985-D056, 1985-D055 are "Eastern Quarterfinal" rather than "EUR QF".

**Comment by Mick1303** [comment]
1985-D019 is an "EASTERN  SEMI-FINAL" rather than "EUR SF"

**Comment by JeffSackmann** [comment]
Should be caught up here. I changed the 2002 G1 tie names to "R1" and "R2" (and "PO1" and "PO2" for the multiple play-off rounds), in keeping with how the Davis Cup site displays them. That might not be a good precedent; to be consistent, that might mean changing a lot of other G1 and G2 tie names. Not sure what the "correct" answer is -- with an eight-team draw, the first round is the QF, but that doesn't sound quite right when no final is ever intended to be played.

**Comment by Mick1303** [comment]
1984-D021: Davis Cup AME QF: CHN vs KOR - shall be "Eastern Quarterfinal"

**Comment by Mick1303** [comment]
1984-D047: Davis Cup AME QF: JPN vs PHI - shall be "Eastern Quarterfinal"

**Comment by Mick1303** [comment]
1984-D054: Davis Cup EUR SF: PAK vs THA - shall be "Eastern Semifinal"

**Comment by Mick1303** [comment]
1984-D020: Davis Cup AME SF: CHN vs JPN  - shall be "Eastern Semifinal"

**Comment by Mick1303** [comment]
1983-D025: Davis Cup AME QF: JPN vs CHN  - shall be "Eastern Quarterfinal"

**Comment by Mick1303** [comment]
Davis Cup WG SF: MEX vs VEN Tid = 1979-D043.  This is not "WG". It is N&C America Semifinal

**Comment by Mick1303** [comment]
Davis Cup WG SF: NZL vs INA 1977 (tid 1977-D033). It is not "WG". It is Eastern. Also Lewis-Tarik match is missing.

**Comment by Mick1303** [comment]
Davis Cup EUR PR: PHI vs THA (tid 1977-D047). It is not "EUR". It is Eastern, Preliminary Round Quarterfinal.
Davis Cup AME PR: PHI vs JPN (tid 1977-D038). It is not "AME". It is Eastern, Preliminary Round Semifinal
Davis Cup WG PR: KOR vs PAK (tid 1977-D040). It is not "WG". It is Eastern, Preliminary Round Semifinal

**Comment by Mick1303** [comment]
Davis Cup EUR PR: TPE vs PHI (tid 1975-D054) is not "EUR". It is Eastern, Preliminary Round Quarterfinal

**Comment by Mick1303** [comment]
Davis Cup WG PR: PHI vs INA (tid 1974-D040) is not "WG". It is Eastern, Preliminary Round 1st Round
