### ISSUE TITLE
Error in assigning surnames and first names for cases of compound first names

### ISSUE THREAD

**Issue by benjdv** [JeffSackmann/tennis_atp#221]
Hi, I found these lines

104273,**Edouard Roger,Vasselin**,R,19831128,FRA,188,Q274441
100486,**Christophe Roger,Vasselin**,R,19570708,FRA,188,Q2966474

instead of 

104273,**Edouard,Roger-Vasselin**,R,19831128,FRA,188,Q274441
100486,**Christophe,Roger-Vasselin**,R,19570708,FRA,188,Q2966474

https://www.wikidata.org/wiki/Q274441
https://www.atptour.com/en/players/edouard-roger-vasselin/r613/overview
=>
Édouard Roger-Vasselin

Maybe same problem for
207663,Nikolas Sanchez,Izquierdo,U,19990315,ESP,,Q106211478 
=> https://www.atptour.com/en/players/nikolas-sanchez-izquierdo/s0gz/overview

100102,Joaquin Loyo,Mayo,R,19450816,MEX,,Q1565143
=> https://www.atptour.com/en/players/joaquin-loyo-mayo/l066/overview

**Comment by benjdv** [comment]
103859,**James**,Cerretani,L,19811002,USA,185,Q717433
=> 103859,**Jamie**,Cerretani,L,19811002,USA,185,Q717433
https://www.atptour.com/en/players/jamie-cerretani/c922/overview
he appears with differents name (For example on this page https://en.wikipedia.org/wiki/James_Cerretani) But I think it's preferable to follow the ATP designation

**Comment by JeffSackmann** [comment]
thanks! I didn't fix James/Jamie -- I generally don't bother with changes like that unless the player (a) is very famous, or (b) the change to/from a more/less formal name is significant or universally done. (e.g. Stanislas -> Stan Wawrinka)
