### ISSUE TITLE
File encoding for ap_player.csv

### ISSUE THREAD

**Issue by ppaulojr** [JeffSackmann/tennis_atp#26]
atp_players.csv seems to be with a weird text encoding.

Line: 

```
112797,Jean Richard,Le Besnerais,,,FRA
112798,Bjã¸Rn,Thalbitzer,,18951213,DEN
112799,Enrique,Obarrio,,,ARG
```

**Comment by beta2k** [comment]
yep. I see the same issue... had to manually change the encoding.

**Comment by JeffSackmann** [comment]
this was fixed at some point in the past
