### ISSUE TITLE
wrong age due to ambigous/duplicate names

### ISSUE THREAD

**Issue by beta2k** [JeffSackmann/tennis_atp#28]
Some player ages (and bio information) are wrong in the match files due to duplicate names of players.

For example `Michael Grant` at the Spain Futures in 2014 is stored as being `58.6` years old. This points to this player: http://www.itftennis.com/procircuit/players/player/profile.aspx?PlayerID=10002555

However, the correct player would be: http://www.itftennis.com/procircuit/players/player/profile.aspx?PlayerID=100129943

This can be proven by looking up the player's match activity on the ITF site. Only the latter one played the Spain Future in 2014.

The next one is similar but a bit trickier because of the variants in name spelling: The player `Adly Shafei` from Egypt occurs, for instance, in the `Egypt 2 Masters 1` from 1996. According to the ITF page he should be named `Adly El Shafei`.

In the database of this repository there are two entries:
`109169,Adli,El Shafei,R,,EGY` (ITF page: http://www.itftennis.com/procircuit/players/player/profile.aspx?playerid=10006597)
`112902,Adly,Shafei,,19190418,EGY` (ITF page: http://www.itftennis.com/procircuit/players/player/profile.aspx?PlayerID=10003427)

For the future from 1996 the first one should be used, however in the match files the second one is used (this can be proven by looking at the age).

Please note that it is very likely that a) there are more wrong occurrences of the mentioned players in other tournaments and match files, and b) that there are more duplicate names, and hence, wrong player information in the match files than mentioned here. These are just two pointers.

I dont think that this issue is super important to resolve since it likely only affects futures matches where due to the player quantity duplicate player names are likely to appear. At least, I can't think of duplicate player names in the ATP circuit...

**Comment by GoldenSlam** [comment]
I know that there have been 2 players named Fernando Gonzalez that were on tour at the same time. One was "Gonzo" the top-ranked player we all probably know, from Chile - the other was a guy from Argentina. You could look at that name if you're looking for other duplicates.

**Comment by JeffSackmann** [comment]
Grant and Shafei are fixed.
