### ISSUE TITLE
Monte-Carlo tourney_level is wrong

### ISSUE THREAD

**Issue by Laurent-Sarrazin** [JeffSackmann/tennis_atp#29]
From what I understand, the "M" level for tournaments stands for Masters 1000. However, Monte-Carlo is tagged with "A" although it's a Masters 1000 tournament.
I've only checked in atp_matches_2015.csv file.

By the way, I'm still scratching my head about what the "A" stands for...

**Comment by mcekovic** [comment]
It is not only Monte Carlo, but also some others Masters 1000 from year 2015, like Shanghai and Paris.

Regards,
Mileta

**Comment by JeffSackmann** [comment]
fixed. (A = ATP, tour-level events that don't fall into a higher category like M = masters or G = grand slam)
