### ISSUE TITLE
Missing many ATP torunaments in '60 and '70

### ISSUE THREAD

**Issue by mcekovic** [JeffSackmann/tennis_atp#34]
Missing many ATP tournaments in '60 and '70, here is the list of some of them that are more important ones:

1979:
- Dorado Beach

1974:
- Auckland

1973:
- Washington-2

1972:
- Roanoke

1971:
- Johannesburg

1970:
- Johannesburg
- Salisbury
- Sydney Outdoor
- Wembley

**Comment by JeffSackmann** [comment]
fixed, with the exception of 1973 washington-2 (I'm assuming that means the Washington Indoor), which is listed on the ATP site, but has no results/draw
