### ISSUE TITLE
Missing World Team Cup at Dusseldorf for 1990

### ISSUE THREAD

**Issue by mcekovic** [JeffSackmann/tennis_atp#35]
Missing World Team Cup at Dusseldorf for 1990,
as well as 10 matches from round-robin stage from 2000,
as well as some of the matches for some other years.

**Comment by JeffSackmann** [comment]
1990 world team cup now included

**Comment by JeffSackmann** [comment]
filled in 80 missing matches from 1998-2010. (looks like none were missing 1991-1997)
