### ISSUE TITLE
Missing round-robin and even one semi-final World Tour Finals matches

### ISSUE THREAD

**Issue by mcekovic** [JeffSackmann/tennis_atp#36]
Some matches from round-robin stage and even one semi-final of World Tour Finals are missing:

Season 2004:
- RR Marat Safin d. Tim Henman 6-2 7-6(2)
- RR Marat Safin d. Guillermo Coria 6-1 6-4

Season 2003:
- RR Carlos Moya d. Rainer Schuettler 7-5 6-4
- RR Rainer Schuettler d. Guillermo Coria 6-3 4-6 6-2

Season 2002:
- RR Carlos Moya d. Marat Safin 6-4 7-5

Season 2000:
- RR Pete Sampras d. Marat Safin 6-3 6-2
- RR Marat Safin d. Lleyton Hewitt 6-4 6-4
- RR Marat Safin d. Alex Corretja 6-7(6) 7-5 6-3
- SF!!!! Andre Agassi d. Marat Safin 6-3 6-3

Season 1999:
- RR Pete Sampras d. Nicolas Lapentti 7-6(2) 7-6(5)
- RR Gustavo Kuerten d. Nicolas Lapentti 6-1 6-2

**Comment by JeffSackmann** [comment]
!!!!
all these are now included
