### ISSUE TITLE
ATP start before birth for player 103541

### ISSUE THREAD

**Issue by rosebyte** [JeffSackmann/tennis_atp#39]
May I've done some bad operation, but it seems that ATP player 103541 (Kevin Harris) had started his ATP career even before he was birth. Is it possible?

**Comment by harman28** [comment]
I don't see this in the data. Could you be more explicit?
Kevin Harris appears to have played only 3 matches, dated 2003, 2009, 2010. His DOB is in 1980. What's the problem?

**Comment by JeffSackmann** [comment]
I see the same as harman28, so presumably no issue here
