### ISSUE TITLE
Incorrect value for Pat Cash atp_rankings_90s CSV

### ISSUE THREAD

**Issue by harman28** [JeffSackmann/tennis_atp#41]
I was trying to find the player who held the largest percentage of available ranking points at any given time, and was surprised to find it was Pat Cash in 1990. Here's the issue:

> 19900416,590,101138,8224

Cash has 8224 points assigned to him for this week at position 590, while Lendl at position 1 had only 3201.

For context, here are the rest of Cash's rankings that month:

> 19900402,617,101138,0
> 19900409,609,101138,13
> 19900416,590,101138,8224
> 19900423,243,101138,90
> 19900430,135,101138,206

If anyone can find Cash's correct score that week, do let me know. Will make the change in my local db as well.

**Comment by harman28** [comment]
A closer look at the ranking file makes it obvious that Cash's score was 14. Don't know what I was thinking.

**Comment by JeffSackmann** [comment]
fixed, thanks
