### ISSUE TITLE
Data dictionary

### ISSUE THREAD

**Issue by Lionrolll** [JeffSackmann/tennis_atp#49]
Hi, 

all these data collected are fascinating however would it be possible to create a data dictionary to better understand what are exactly some of the fields. For example, in the file atp_matches_2016; there is a variable called tourney_level that can take the value 'G', 'M', 'A', 'D' and I don't know what these categories refer to. In the statistics provided in other tables, it would be also interesting to know what they mean or how they were derived. 

Of course, I understand it is an important effort but it's really worth to help understanding in tennis statistics. 

Do you think it is something that you could share with the community? 

Thanks!

**Comment by mcekovic** [comment]
Hi,

'G', 'M', 'A', 'D':
G - Grand Slam
M – Masters
A – ATP (500 & 250)
D – Davis Cup
O – Olympics
…

Re statistics columns, you have header at in the first row (If you know tennis sport you will know the meaning ☺). Btw stats columns are very cleverly defined, as they represent the minimum number of columns from which other stats can be derived, like first server percentage, points won on first serve percentage, points won on second server percentage, total service points pct, break points conversion pct, etc…
Winners/UFOs are lacking, but this data is not available even in ATP official site.

Btw. I have built a Tennis stats based on Jeffs data (with some corrections and some of my own data where it was lacking), you might find there what you need:
http://tennis-strangeforest.rhcloud.com

Regards,
Mileta
