### ISSUE TITLE
Duplicate tournament in atp_matches_1971.csv Montreal / Toronto & Toronto WCT

### ISSUE THREAD

**Issue by mcekovic** [JeffSackmann/tennis_atp#50]
1971-421,Montreal / Toronto,Clay
1971-302,Toronto WCT,Carpet
All matches, including final one John Newcombe (1) d. Tom Okker (2) 7-6 3-6 6-2 7-6, are the same.
Difference is only that Toronto WCT does not have seeds and has wrong surface.

**Comment by JeffSackmann** [comment]
fixed
