### ISSUE TITLE
Rankings missing for 1982 and 1983

### ISSUE THREAD

**Issue by harman28** [JeffSackmann/tennis_atp#55]
`atp_rankings_80s.csv` has just one week of rankings each for 1982 and 1983.

**Comment by mcekovic** [comment]
Please note that in that period, ATP lost their ranking. You would not find it neither on ATP official web site (for example http://www.atpworldtour.com/en/rankings/singles?rankDate=1982-01-04&rankRange=0-100 ).
I think some work has been done by independent people to restore these rankings, but it is not official.

**Comment by harman28** [comment]
Oh wow. I did not know this. Do you have any sources where I can read more about this?

**Comment by mcekovic** [comment]
Very good rankings data source: http://www.menstennisforums.com/2730-advanced-discussions/764513-rankings-database-%5Bversion-2%5D.html
