### ISSUE TITLE
2016_Tour_Finals

### ISSUE THREAD

**Issue by kaktusz65** [JeffSackmann/tennis_atp#57]
Hi,

In 2016 atp dataset the yearend Tour Finals is marked as tour_level 'A' instead of "F". The name is "London" instead of Tour Finals.

Regards

Zoltan

**Comment by mcekovic** [comment]
This is a duplicate of https://github.com/JeffSackmann/tennis_atp/issues/48

**Comment by JeffSackmann** [comment]
fixed
