### ISSUE TITLE
Incomplete rankings for certain dates

### ISSUE THREAD

**Issue by jerzyt** [JeffSackmann/tennis_atp#6]
Hi,
Many thanks for this great dataset.  I've tried doing that a while ago and gave up, because I didn't have the bandwidth to deal with the messy data issues.
I noticed that some of the dates have incomplete ranking information.  For example, 2010-09-06 has only the players ranked 1,001 and lower - the top 1,000 players are missing.
This became evident when I looked at the total number of ranking points each week.
Thanks,
Jerzy

**Comment by JeffSackmann** [comment]
Occasionally that's what's on the ATP site, especially mid-week during slams (which is probably was 2010-09-06 is). Let me know if you find specific dates where the ATP site or some other source shows rankings that are not included here.
