### ISSUE TITLE
Duplicate value in ATP player file

### ISSUE THREAD

**Issue by mmmarsbarrr** [JeffSackmann/tennis_atp#62]
I think 'Aj Catanzariti' is a duplicate ATP player entry, player ID's are 126272 and 200224

**Comment by mcekovic** [comment]
It is not the only duplicate introduced recently, there are many :(

**Comment by mmmarsbarrr** [comment]
This was the only duplicate I could find amongst both the ATP and WTA player files based on first and last name combined? Are you able to share more information regarding the other duplicates?

**Comment by JeffSackmann** [comment]
fwiw, there are no matches or rankings associated with 200224. I'm not going to delete that record just in case there's something lurking in other files on my end associated with 200224
