### ISSUE TITLE
Some W/O have a blank space in front "W/O" and " W/O"

### ISSUE THREAD

**Issue by haroldmk** [JeffSackmann/tennis_atp#64]
While comparing career W-L of some players I realized that the data provided for the files were not entirely correct.
Then I discovered that some walkover data were wrong typed most walkover are set as "W/O" (3 characters) but some matches (apparently random) were set as " W/O" with a blank space in front of the "W" for a total of 4 characters.
Using Excel the filters provide that there are 3 types of "W/O" but I haven't realized which is the third type.

**Comment by mcekovic** [comment]
Maybe this can help:

				switch (set) {
					case 'W/O':
					case '(W/O)':
					case 'Walkover': outcome = 'W/O'; break
					case 'RET':
					case '(RET)': outcome = 'RET'; break
					case 'ABD':
					case 'ABN':
					case '(ABN)':
					case 'abandoned':
					case 'unfinished':
					case 'Unfinished': outcome = 'ABD'; break
					case 'Default':
					case 'DEF': outcome = 'DEF'; break
					case 'NA': return null
					case 'In':
					case 'Progress':
					case 'Played':
					case 'and': break
					default: println("Invalid set outcome: $set")
				}
