### ISSUE TITLE
Data Scraping Scripts

### ISSUE THREAD

**Issue by jgollub1** [JeffSackmann/tennis_atp#66]
Hi Jeff,

Thank you so much for everything you do and all the data you've put on GitHub. Just last fall I submitted my undergraduate thesis after six months of working with your match and point-by-point data. I am writing now because I think it would be helpful to the tennis analytics community if you also shared the scripts you use to scrape data and produce the match datasets in 'tennis_atp' as well as the point-by-point data in 'tennis_point_by_point'. 

For one, this would allow greater transparency for everyone who uses your datasets. As your datasets have been used in various academic papers and the five thirty eight blog, I think it would be helpful for all parties involved to know exactly where the data has come from. For example, I conducted my own undergrad thesis with your point-by-point data without actually knowing where the data came from (now, I suspect https://www.scoreboard.com/tennis/ or something similar). I don't think I've actually seen any academic papers using your point-by-point data but I think it would be really useful for everyone to clarify its source because there are so many interesting research questions to tackle with point-by-point data.

In addition, posting the scripts would allow the rest of the community to fix many of the small issues found in your datasets, saving you the trouble of facing a stream of unresolved issues. If you allow other people to contribute, then the community could work together to further improve the quality of match data.

Finally, this would allow everyone to keep your match dataset up-to-date. For anyone hoping to produce weekly elo ratings on their own, they must find a way to fill in the matches since your most recent GitHub update (which was three months ago in Feb 2018 at this point). I have noticed that you keep weekly elo ratings at http://tennisabstract.com/reports/atp_elo_ratings.html, which implies that you update your own match database every week. Of course, I can just directly scrape the elo ratings from your site but I wouldn't be able to keep up to date serve/return statistics, or other stats of interest. Right now, the only solution is for me to patch together your match dataset with some newly scraped data using the unofficial atpworldtour API (https://github.com/serve-and-volley/atp-world-tour-tennis-data), which is completely possible but not ideal since formatting inconsistencies may arise between the two. I'd love to hear from you, regardless of whether this may be possible. Thanks again for all you do,

-Jacob

**Comment by mcekovic** [comment]
Hi Jacob,

Please note web scrapping is in the 'gray' legal area, and unofficial '[robots.txt](http://www.atpworldtour.com/robots.txt)' on ATP Web site explicitly mentions results archive.

Although idea of community maintained tennis data set is great, public web scrapping scripts is better to avoid, so the project for ATP web scrapping you mentioned is hardly something to be considered for a community based project. Note that ATP data itself is full or errors, so community may help to tidy the data, just that how data is obtained, should not be publicly stated.

Regards,
Mileta
(owner of [Ultimate Tennis Statistics](http://www.ultimatetennisstatistics.com/), website (mostly) based on Jeff's historical data, with custom additions and corrections)
