### ISSUE TITLE
Tournament id's

### ISSUE THREAD

**Issue by jgollub1** [JeffSackmann/tennis_atp#67]
I'm seeing tournament ids in the atp match dataset change over the past few years. Note the following examples,

Acapulco 2015: '2015-807'
Acapulco 2016: '2016-M004'

Beijing 2015: '2015-747'
Beijing 2016: '2016-M015'

Brisbane 2015: '2015-339'
Brisbane 2016: '2016-M020'

...

It looks like the underlying tournament id's (in format '%y-%id') of existing tournaments were changed between 2015 and 2016. Has this change been charted in another file? I use the tournament id's to cross reference historical statistics from a tournament's previous years. Since the tourney_name itself can also be inconsistent (Indian Wells --> Indian Wells Masters, etc), I was hoping to use the tournament id's. Thanks!

-Jacob

**Comment by mcekovic** [comment]
2015 tournament IDs contain (like most of the tournament IDs) external ID from ATP web site, like for Brisbane 2018: http://www.atpworldtour.com/en/scores/archive/brisbane/339/2018/results

2016 are some intermediate IDs used by Jeff at some point in time or some error in the scrapping scripts.
