### ISSUE TITLE
Alexander Zverev

### ISSUE THREAD

**Issue by samperochkin** [JeffSackmann/tennis_atp#68]
There seems to have a little confusion concerning Alexander Zverev in the ranking files. His father, who is also called Alexander Zverev (Sr), played in the 80s. There is a player called

Xxxxx Zverev

in the atp_players dataset, with id=125903. It's data of birth is NA and hand is U... If it is indeed Alexander Zverev Sr, then its date of birth is January 22, 1960 (wikipedia).

The real problem appears in the atp_rankings dataset for the 80s. The player identified is Alexander Zverev (id=100644), which does not make sense.

Great repo, thx.

**Comment by JeffSackmann** [comment]
fixed. all instances of zverev sr moved to id 200630

**Comment by bazzaar** [comment]
> fixed. all instances of zverev sr moved to id 200630

Unfortunately, there seems to have been a typo error in this update of the `atp_rankings_80s.csv` file, as discovered by 'peteshub' 12-Jan-2019 : 

id # **200603** was substituted for the previously incorrect occurrences of # 100644
