### ISSUE TITLE
There are some strange characters/strings in the 'atp_matches_futures_2017.csv' file.

### ISSUE THREAD

**Issue by CQH** [JeffSackmann/tennis_atp#70]
@JeffSackmann,  there are some strange characters/strings in the 'atp_matches_futures_2017.csv' file. They were screwing up some data imports for me. 

Offending strings/character:
- `&nbsp;` 
- `Â`

They were all in the 'score' column.

I have created a pull-request that fixes the 5 rows. : https://github.com/JeffSackmann/tennis_atp/pull/69

**Comment by JeffSackmann** [comment]
fixed
