### ISSUE TITLE
Numeric codes in player names

### ISSUE THREAD

**Issue by hgrano** [JeffSackmann/tennis_atp#71]
I have noticed that  certain players have numeric values in their names. For examples, atp_players.csv contains

```
100458,Pedro,Gonzalez G162,R,19561218,PUR
```

This appears to correspond to the atp website's player code https://www.atpworldtour.com/en/players/pedro-gonzalez/g162/overview

Is this intentional or should this be corrected? Happy to do a PR to correct this if needed.

**Comment by mcekovic** [comment]
I suppose this is because there is another Pedro Gonzalez, from Venezuela (VEN), born 1993, while Pedro Gonzalez (PUR) is born in 1956.

**Comment by JeffSackmann** [comment]
yes, the code is used to differentiate between players with the same name
