### ISSUE TITLE
Grand Slams PBP dictionary

### ISSUE THREAD

**Issue by vincentanutama** [JeffSackmann/tennis_atp#72]
I was wondering if folks on this repo might know what the following variables and entries in the grand slams PBP data meant:
ServeWidth = {"B", "BC", "BW", "C", "W"}
ServeDepth = {"CTL", "NCTL"}
ReturnDepth = {"D", "ND"}
ServeIndicator = {1, 2}
Serve_Direction = {0, 1, 2, 3}

I opened the same issue in the grand slams pbp repo but wasn't sure which one would be more appropriate. Thanks!

**Comment by JeffSackmann** [comment]
it's more appropriate in the relevant repo
