### ISSUE TITLE
Error in player name "Antonie Hoang" > "Antoine Hoang"

### ISSUE THREAD

**Issue by mdolr** [JeffSackmann/tennis_atp#76]
I would gladly correct the mistake but I'm confused with how this repo works so I'll just make an issue.

The player named "Antonie Hoang" should be named "Antoine Hoang" https://en.wikipedia.org/wiki/Antoine_Hoang

**Comment by mcekovic** [comment]
There are some other misspells and other player name issues. Most notably:
- Mcenroe -> McEnroe (John and Patrick!)
- Stanislas Wawrinka -> Stan Wawrinka
- Francis Tiafoe -> Frances Tiafoe 

But there are others
- Alexander Lazov -> Alexandar Lazov
- Andre Tielemans -> Andre Thielemans
- Andres Artunedo Martinavarr -> Andres Artunedo Martinavarro
- Antonie Hoang -> Antoine Hoang
- Ben Fatael -> Ben Patael
- Evgeny Tyurnev -> Evgenii Tiurnev
- Franco Skugor -> Franko Skugor
- Gianni Capozza -> Giovanni Capozza
- Hans Jaochim Plotz -> Hans Joachim Ploetz
- Han Jurgen Pohmann -> Hans Jurgen Pohmann
- Djurabek Karimov -> Jurabek Karimov
...

**Comment by JeffSackmann** [comment]
fixed these and many others
