### ISSUE TITLE
ATP match data : some unlikely match scores?

### ISSUE THREAD

**Issue by bazzaar** [JeffSackmann/tennis_atp#81]
Hi,

I'm loading (and then qc'ing) the atp/wta tennis data from your repo's into a postgres db, purely non-commercial use, basically a hobby project to learn all aspects of data handling and analysis.

A small piece of that is taking the match score text string and converting it into a useable data array.

I've noticed some unlikely match scores, and detailed them below. I'll add more as they crop up. (will likely create a similar ticket for the wta match scores too).

I hope this is of some help.
bazzaar

 tourney_type  | tourney_id | tourney_name | surface | draw_size | tourney_level | tourney_date | match_num | winner_id | winner_seed | winner_entry | winner_name | winner_hand | winner_ht | winner_ioc |  winner_age   | winner_rank | winner_rank_points | loser_id | loser_seed | loser_entry |     loser_name     | loser_hand | loser_ht | loser_ioc |   loser_age   | loser_rank | loser_rank_points |      score      | best_of | round | minutes | w_ace | w_df | w_svpt | w_1stin | w_1stwon | w_2ndwon | w_svgms | w_bpsaved | w_bpfaced | l_ace | l_df | l_svpt | l_1stin | l_1stwon | l_2ndwon | l_svgms | l_bpsaved | l_bpfaced | conclusion 
---------------+------------+--------------+---------+-----------+---------------+--------------+-----------+-----------+-------------+--------------+-------------+-------------+-----------+------------+---------------+-------------+--------------------+----------+------------+-------------+--------------------+------------+----------+-----------+---------------+------------+-------------------+-----------------+---------+-------+---------+-------+------+--------+---------+----------+----------+---------+-----------+-----------+-------+------+--------+---------+----------+----------+---------+-----------+-----------+------------
 ATP Main Draw | 1994-438   | Moscow       | Carpet  |        32 | A             | 1994-11-07   |        27 |    101820 |           6 |              | Marc Rosset | R           |       201 | SUI        | 24.0000000000 |          15 |               1782 |   102338 |          3 |             | Yevgeny Kafelnikov | R          |      190 | RUS       | 20.7173169062 |         11 |              2172 | 5-7(12) 6-4 6-3 |       3 | QF    |     132 |    20 |   10 |    104 |      57 |       48 |       27 |      16 |         2 |         2 |     8 |    6 |    101 |      47 |       38 |       32 |      15 |         4 |         6 | 

`## atp_matches_1994.csv`
`## same as on atp archive website, quessing this should be 6-7(12),6-4,6-3 (unverified)`

 ATP Main Draw | 1996-573   | Marbella     | Clay    |        32 | A             | 1996-09-30   |        28 |    102456 |           2 |              | Felix Mantilla | R           |       180 | ESP        | 22.0205338809 |          16 |               1576 |   102104 |            |             | Christian Ruud | R          |      188 | NOR       | 24.1013004791 |         62 |               743 | 0-7 7-6(2) 6-3 |       3 | QF    |     134 |     4 |    1 |     93 |      60 |       31 |       15 |      13 |         6 |        14 |     2 |    5 |     94 |      57 |       31 |       14 |      14 |         0 |         7 | 

`## atp_matches_1996.csv`
`## same as on atp archive website, quessing this should be 5-7,7-6(2),6-3 (unverified)`

 ATP Main Draw | 1972-343   | Columbus     | Hard    |        32 | A             | 1972-07-23   |         4 |    100094 |             |              | Jim Osborne   | R           |       185 | USA        | 27.4715947981 |             |                    |   107810 |            |             | Mike Kreiss  | R          |          | USA       |               |            |                   | 3-7     |       3 | R32   |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           |
 
`## atp_matches_1972.csv`
`## should be 6-3,7-5 (verified  - https://www.atpworldtour.com/en/scores/archive/columbus/343/1972/results?round=R32&player=K132)`
 
 ATP Main Draw | 1979-402   | Memphis      | Carpet  |        64 | A             | 1979-02-26   |        37 |    100255 |           7 |              | Roscoe Tanner | L           |       183 | USA        | 27.3675564682 |          11 |                  0 |   100280 |         12 |             | Wojtek Fibak | R          |      183 | POL       | 26.5653661875 |         21 |                 0 | 3-7 5-0 |       3 | R16   |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 

`## atp_matches_1979.csv`
`## guess should be 6-3,7-5 (unverified)`

 ATP Challenger Quals | 2007-1683  | Sarajevo CH  | Hard    |        32 | C             | 2007-03-12   |        28 |    105208 |           2 |              | Ernests Gulbis | R           |       190 | LAT        | 18.5297741273 |             |                    |   104056 |          6 |             | Roko Karanusic | R          |      183 | CRO       | 24.5147159480 |            |                   | 1-6(4) 6-7(3) 6-4 |       3 | QF    |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 

`## atp_matches_qual_chall_2007.csv`
`## quess should be 7-6(4) 6-7(3) 6-4`

 ATP Challenger Quals | 2000-457   | Milan CH     | Carpet  |        32 | C             | 2000-12-04   |        25 |    102433 |             |              | Mose Navarra    | L           |       180 | ITA        | 26.3819301848 |         253 |                133 |   102565 |            |             | Alexander Waske | R          |      188 | GER       | 25.6810403833 |        265 |               124 | 2-6(3) 7-6(5) 7-6 |       3 | QF    |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 
 
`## atp_matches_qual_chall_2000.csv`
`## quess should be 7-6(3) 7-6(5) 7-6`
 
 ATP Main Draw        | 1991-375   | Lyon         | Carpet  |        32 | A             | 1991-10-14   |        21 |    101606 |           6 |              | Alberto Mancini | R           |       180 | ARG        | 22.4010951403 |          22 |               1022 |   101900 |            |             | Nicklas Kulti   | R          |      190 | SWE       | 20.4791238877 |         60 |               528 | 2-6(8) 7-6 6-4    |       3 | R16   |     124 |     7 |    2 |     85 |      56 |       41 |       10 |      11 |         2 |         5 |     3 |    1 |     82 |      53 |       34 |       13 |      11 |         5 |         9 | 
(2 rows)

`## atp_matches_1991.csv`
`## quess should be 7-6(8) 7-6 6-4`

 ATP Futures          | 2000-M-SA-ITA-03A-2000c | Italy 3 3    | Clay    |        32 | S             | 2000-06-19   |        24 |    102400 |           2 | Q            | Elia Grossi            | R           |           | ITA        | 26.0451745380 |         375 |                 70 |   102638 |            |             | Christian Persico | U          |          | ITA       | 24.8624229979 |       1022 |                 4 | 4-6(4) 6-3 6-3      |       3 | R16   |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 
 
`## atp_matches_futures_2000.csv`
`## quess should be 7-6(4) 6-3 6-3`
 
 ATP Main Draw        | 1977-406                | Brussels     | Clay    |        64 | A             | 1977-06-06   |        34 |    100271 |             |              | Jean Francois Caujolle | L           |           | FRA        | 25.1827515400 |          95 |                  0 |   100233 |            |             | Ricardo Cano      | R          |      170 | ARG       | 26.2751540041 |         51 |                 0 | 4-6(4) 6-0 10-8 4-6 |       5 | R16   |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 
 
`## atp_matches_1977.csv`
`## verified should be 4-6 6-0 10-8`
`## also ... was a 'best of 3 sets' match, not 5 - update 'best_of'`
 
 ATP Challenger Quals | 2007-23                 | Chennai Q    | Hard    |           | Q             | 2007-01-01   |        25 |    105053 |             |              | Santiago Giraldo       | R           |       188 | COL        | 19.0965092402 |         175 |                230 |   103248 |            |             | Harel Levy        | R          |      185 | ISR       | 28.4079397673 |        286 |               134 | 4-6(4) 6-4 7-6      |       3 | Q3    |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 

`## atp_matches_qual_chall_2007.csv`
`## quess should be 4-6 6-4 7-6(4)`

 ATP Futures  | 2012-M-FU-CRO-02A-2012 | Croatia F2   | Hard    |        32 | S             | 2012-02-20   |        29 |    105888 |           7 |              | Toni Androic | U           |           | CRO        | 20.1478439425 |         345 |                124 |   103748 |            |             | Jan Minar  | R          |          | CZE       | 30.8665297741 |        375 |               106 | 30-40 |       3 | SF    |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | retired

`## atp_matches_futures_2012.csv`
`## quess should be 0-0 in games, not 30-40 in points`

 ATP Main Draw | 2007-506   | Buenos Aires | Clay    |        32 | A             | 2007-02-19   |        33 |    103701 |             | WC           | Diego Hartfield | R           |       185 | ARG        | 26.0506502396 |         117 |                380 |   104076 |          8 |             | Jose Acasuso | R          |      190 | ARG       | 24.3340177960 |         41 |               815 | 3-Jun |       5 | RR    |      52 |     0 |    2 |     30 |      17 |       14 |        6 |       4 |         1 |         1 |     1 |    3 |     45 |      15 |        8 |       15 |       5 |         4 |         6 | 

`## atp_matches_2007.csv`
`## verified should be 6-3 (not 3-Jun) presumably RET`

 ATP Main Draw | 1972-560   | US Open      | Grass   |       128 | G             | 1972-08-30   |        23 |    100160 |             |              | Georges Goven | R           |       173 | FRA        | 24.3449691992 |             |                    |   100299 |            |             | James Chico Hagey | R          |          | USA       | 19.5099247091 |            |                   | 0-15  |       5 | R128  |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | retired

`## atp_matches_1972.csv`
`## verified should be 0-0 in games, not 0-15 in points` 

 ATP Challenger Quals | 1993-758   | Venice CH    | Clay    |        32 | C             | 1993-09-06   |        29 |    101507 |           3 |              | Tomas Carbonell | R           |       178 | ESP        | 25.0814510609 |             |                    |   101746 |          1 |             | Renzo Furlan | R          |      175 | ITA       | 23.3073237509 |            |                   | 93-2 6-1 |       3 | SF    |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 

`## atp_matches_qual_chall_1993.csv`
`## verified should be 6-2 6-1 (http://www.stevegtennis.com/draw-results/atp/Venice_Challenger/1993/)`

 ATP Main Draw | 1983-321                | Stuttgart Outdoor    | Clay    |        32 | A             | 1983-07-11   |         3 |    100411 |             |              | Pavel Slozil    | R           |       173 | CZE        | 27.0143737166 |          49 |                  0 |   100606 |            |             | Mike Bauer        | R          |      188 | USA       | 23.5154004107 |         89 |                 0 | 4-7 6-4 6-1 |       3 | R32   |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 
 
`## atp_matches_1983.csv`
`## verified should be 5-7 6-4 6-1`
 
 ATP Futures   | 1991-M-SA-FIN-01A-1991b | Finland Masters 2    | Clay    |        32 | S             | 1991-06-10   |         6 |    101629 |             | Q            | Matt Lucena     | R           |       178 | USA        | 21.8480492813 |             |                    |   102395 |            | WC          | Ville Liukko      | R          |      173 | FIN       | 17.0458590007 |            |                   | 4-7 6-3 6-0 |       3 | R32   |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 
 
`## atp_matches_futures_1991.csv`
`## quess should be 5-7 6-3 6-0`
 
 ATP Main Draw | 1978-560                | US Open              | Hard    |       128 | G             | 1978-08-29   |        74 |    100173 |             |              | Andrew Pattison | R           |       188 | USA        | 29.5770020534 |         100 |                  0 |   100090 |            |             | Dick Crealy       | R          |          | AUS       | 33.9438740589 |         85 |                 0 | 4-7 7-6 6-2 |       5 | R64   |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 
 
`## atp_matches_1978.csv`
`## verified should be 4-6 7-6 6-2`
 
 ATP Futures   | 1991-M-SA-YUG-01A-1991b | Yugoslavia Masters 2 | Clay    |        32 | S             | 1991-04-06   |        10 |    101959 |             |              | Robert Eriksson | R           |           | SWE        | 19.5646817248 |         518 |                 21 |   101824 |            | SE          | Marcello Molinari | R          |          | ITA       | 20.3805612594 |            |                   | 4-7 7-5 6-4 |       3 | R32   |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 
 
`## atp_matches_futures_1991.csv`
`## quess should be 5-7 7-5 6-4 with 1st set tiebreak not recorded?`

 ATP Futures  | 1995-M-SA-RUS-01A-1995b | Russia Masters 2 | Clay    |        32 | S             | 1995-07-29   |        28 |    102666 |           8 |              | Thomas Strengberger S597 | R           |           | AUT        | 19.8001368925 |         608 |                 23 |   101484 |          2 |             | Vladimir Gabrichidze | R          |      175 | GEO       | 27.1868583162 |        977 |                 6 | 3-6 7-1 |       3 | QF    |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | defaulted

`## atp_matches_futures_1995.csv`
`## quess should be 3-6 6-1 defaulted ??`

 ATP Challenger Quals | 2007-3633  | Belo Horizonte CH | Clay    |        32 | C             | 2007-10-22   |        29 |    103534 |           7 |              | Nicolas Devilder | L           |       173 | FRA        | 27.5756331280 |         124 |                341 |   104593 |            | Q           | Daniel Gimeno Traver | R          |      185 | ESP       | 22.2067077344 |        222 |               178 | 7-6(3) 7-2 |       3 | SF    |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 

`## atp_matches_qual_chall_2007.csv`
`## verified should be 7-6(3) 6-2`

 ATP Challenger Quals | 2007-3535  | Rimouski CH  | Carpet  |        32 | C             | 2007-10-22   |        21 |    105028 |             |              | Jesse Levine | L           |       175 | CAN        | 20.0191649555 |         429 |                 69 |   104897 |          4 |             | Matthias Bachinger | R          |      188 | GER       | 20.5557837098 |        208 |               196 | 7-6(3) 7-3 |       3 | R16   |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 
(1 row)

`## atp_matches_qual_chall_2007.csv`
`## verified should be 7-6(3) 6-3`

 ATP Futures  | 1991-M-SA-BRA-03A-1991a | Brazil 3 Masters 1 | Clay    |        32 | S             | 1991-05-13   |         8 |    107589 |           6 |              | Luis Andreotti | R           |           | ARG        |            |         481 |                 24 |   108139 |            |             | Roberto Teofilo | R          |          | BRA       |           |        642 |                12 | 6-1 7-3 |       3 | R32   |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 

`## atp_matches_futures_1991.csv`
`## quess should be 6-1 6-3  ??? or 6-1 7-5 ??? or 6-1 7-6 ???`

 ATP Main Draw | 1981-424   | San Francisco | Carpet  |        64 | A             | 1981-09-21   |        10 |    100436 |             |              | Nick Saviano | L           |       180 | USA        | 25.2950034223 |          96 |                  0 |   100522 |            |             | Chris Dunk | R          |      193 | USA       | 23.6605065024 |            |                   | 7-6 7-3 |       3 | R64   |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 

`## atp_matches_1981.csv`
`## verified should be 7-6 6-3, (1st set tiebreak not recorded)`
`## last match listed on ATP tourney webpage`

 ATP Main Draw | 1974-424   | San Francisco | Carpet  |        64 | A             | 1974-09-23   |         2 |    100171 |             |              | John Yuill  | R           |           | RSA        | 25.7796030116 |          81 |                  0 |   100116 |            |             | Sherwood Stewart | R          |      188 | USA       | 28.2984257358 |         71 |                 0 | 7-6 7-3 |       3 | R64   |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 

`## atp_matches_1974.csv`
`## verified should be 7-6 6-3, (1st set tiebreak not recorded) `
`## also last match listed on ATP tourney webpage`

 ATP Main Draw | 1972-414   | Hamburg      | Clay    |        32 | A             | 1972-06-05   |         5 |    100025 |             |              | Barry Phillips Moore | R           |       173 | AUS        | 34.9075975359 |             |                    |   100220 |            |             | Jiri Hrebec | R          |          | CZE       | 21.7111567420 |            |                   | 7-5 7-3 |       3 | R32   |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 

`## atp_matches_1972.csv`
`## verified should be 7-5 6-3`
`## last match in the R32 section on the tournament results webpage, and R64 results missing in this repo`

 ATP Futures  | 1998-M-SA-AUS-01A-1998d | Australia 1 Masters 4 | Hard    |        32 | S             | 1998-03-01   |        29 |    102842 |           7 |              | Toby Mitchell | R           |           | AUS        | 21.5304585900 |         447 |                 63 |   103308 |            | WC          | Sebastian Swierk | R          |          | AUS       | 19.1266255989 |        750 |                16 | 5-7 7-4 7-5 |       3 | SF    |         |       |      |        |         |          |          |         |           |           |       |      |        |         |          |          |         |           |           | 

`## atp_matches_futures_1998.csv`
`## quess should be 5-7 6-4 7-5`

**Comment by JeffSackmann** [comment]
fixed the invalid scores, and added 1972 hamburg R64 matches.
