### ISSUE TITLE
Alexander Zverev #68 - 'commit_8c2645f_zverev_sr_bugfix' has created new problems

### ISSUE THREAD

**Issue by bazzaar** [JeffSackmann/tennis_atp#82]
Hi, 

The 'commit_8c2645f_zverev_sr_bugfix' was completed in response to #68  and that issue was subsequently closed. This commit has, however, created new problems in 2 areas : 

 - Rankings : the **wrong** `id` for `Alexander Zverev Sr` was used in the substitution, ( 200603 instead of the correct id # 200630 ). Thanks to 'peteshub' for pointing this out, see the comment below, and for details see bazzaar's comment attached to issue #68 . The only rankings file impacted is `atp_rankings_80s.csv`, now with 220 erroneous records. Note the earliest ranking data for 'Alexander Zverev Sr' is from 1982, therefore the 'commit_8c2645f_zverev_sr_bugfix' did not touch the ranking_70s file.

- Match data : the 'commit_8c2645f_zverev_sr_bugfix' changed the player `id` in the match files, using the **correct** `id` for 'Alexander Zverev Sr' (200630), but it didn't change the associated player details in those match files, so (winner/loser) name/ioc (and possibly other player related fields to a very minor extent) are now incorrect  on the modified records.

It seems the only player related fields that are consistently populated, in this case, are 

`winner_name, winner_hand, winner_ioc, loser_name, loser_hand, loser_ioc`

Neither winner_hand/loser_hand needs changing (both Alexander Sverev's are right handed).

So the required fix for the match data is : 

- winner_name/loser_name, change 'Alexander Zverev' --> 'Alexander Zverev Sr'.
- winner_ioc/loser_ioc, change 'GER' --> 'RUS'.

This, importantly, is only for matches from 1979 - 1987 inclusive.

These are the match counts by year, after the 'commit_8c2645f_zverev_sr_bugfix'

`  year |   id_org | winning | losing` 
` 1987 |   200630 |       0 |      2`
` 1986 |   200630 |       0 |      4`
` 1985 |   200630 |       1 |      6`
` 1984 |   200630 |       4 |      2`
` 1983 |   200630 |       1 |      1`
` 1982 |   200630 |       2 |      2`
` 1981 |   200630 |       3 |      0`
` 1979 |   200630 |       2 |      0`
(8 rows)

Hope this helps.
bazzaar

**Comment by JeffSackmann** [comment]
afaict, all incorrect references to 200603 are gone; all references to 100644 for zverev sr are gone, and the zverev sr matches all have correct bio and ranking data in the match results files.
