### ISSUE TITLE
ATP match data : 2017 Germany F3 and F4 tournaments share the same tourney_id

### ISSUE THREAD

**Issue by bazzaar** [JeffSackmann/tennis_atp#84]
Hi,
It looks like the 2017 Germany F3 tournament matches have all been assigned to the Germany F4 tournament (id 2017-M-FU-GER-04A-2017), erroneously resulting in twice as many matches (62) as there should be in the latter. The data should look like this in summary `:`
 
`tourney_type |       tourney_id                      | tourney_name | tourney_date | surface | count_matches` 
`ATP Futures  | 2017-M-FU-GER-03A-2017 | Germany F3    | 2017-01-23    | Carpet |    31`
`ATP Futures  | 2017-M-FU-GER-04A-2017 | Germany F4    | 2017-06-19    | Clay     |    31`

Hope this helps
bazzaar

**Comment by JeffSackmann** [comment]
looks like I deleted germany f3 in my attempt to fix this. So now it's a new issue: 2017 germany f3 is missing.

**Comment by bazzaar** [comment]
Those pesky duuplicates :-), they can be tricky to remove. I can send you the data as I've loaded it, if that would be of help?

**Comment by JeffSackmann** [comment]
thanks, I had all the data as well, had just ham-handedly deleted it to solve the dupe ID issue.
