### ISSUE TITLE
ATP match data : whole tournaments duplicated [twice] 

### ISSUE THREAD

**Issue by bazzaar** [JeffSackmann/tennis_atp#85]
Hi,

This issue builds on a previous one (#10 2002 Wrexham ch).

All of the match data for the following tournaments are duplicated [twice] in the same fashion.

`tourney_id  |         tourney_name                    | tourney_date`
`2011-6406  | ATP Challenger Tour Finals CH | 2011-11-14  `
`2012-6406  | ATP Challenger Tour Finals CH | 2012-11-27  `
`2013-6406  | ATP Challenger Tour Finals CH | 2013-11-11  `
`2015-6406  | Challenger Tour Finals               | 2015-11-23  `
`2010-5059  | Curitiba CH                                | 2010-04-19  `
`2002-782    | Wrexham CH                             | 2002-07-29  `

There is a single copy of the tourney match data in the ATP file of that year, and then there are two exact copies of that same data in the ATP_Chall_Qual file of that year.

I checked that all the data is exactly duplicated, by utilising the 'select/except/select' construct in postgresql, but this could also be verified in the files using grep/sort -u/diff on the command line.   

The issue #10 (2002 Wrexham ch) also highlights the unauthodox match numbering in the Wrexham data, and a couple of missing matches.

This same unauthodox match numbering pattern occurs in both the `2010-5059 Curitiba CH 2010-04-19` and `2011-6406 ATP Challenger Tour Finals CH 2011-11-14` tournaments data also. On this basis, perhaps issue #10 could be closed, and it's issue be rolled up into this one, going forward.

Hope this helps,
bazzaar

**Comment by JeffSackmann** [comment]
looks like these are all fixed now, thanks
